include: package:pedantic_mono/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
custom_lint:
  rules:
    # Project uses [UncontrolledProviderScope] so we can disable this rule
    - missing_provider_scope: false
