name: github_search_app
description: Github Search App
publish_to: 'none'

version: 1.0.0+1



environment:
  sdk: ^3.3.1
  flutter: ^3.19.3
dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.1
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_hooks_lint: ^1.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  pedantic_mono: ^1.26.0
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true