name: github_search_app
description: Github Search App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3
dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.1
  hooks_riverpod: ^2.5.1
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  slang: ^3.30.1
  slang_flutter: ^3.30.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  pedantic_mono: ^1.26.0
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  slang_build_runner: ^3.30.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700

flutter_gen:
  output: lib/src/core/gen

  integrations:
    flutter_svg: true
