name: "Setup Application Runtime"
description: "Setup the application runtime for Flutter"

runs:
  using: "composite"
  steps:
    # https://github.com/kuhnroyal/flutter-fvm-config-action
    - name: Fetch flutter config
      uses: kuhnroyal/flutter-fvm-config-action@v2
      id: fvm-config-action

    # https://github.com/subosito/flutter-action
    - name: Setup flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
