name: Auto Assign

on:
  pull_request:
  types: [ opened, ready_for_review ]

permissions:
  pull-requests: write

jobs:
  request-assignees:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      # https://github.com/marketplace/actions/review-assign-action
      - name: Request assignees
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          ready-comment: 'Ready for review :rocket:'