name: check-pr

on:
    pull_request:

jobs:
    pre-check:
        permissions:
          pull-requests: write
        outputs:
          src: ${{ steps.check.outputs.src }}
        runs-on: ubuntu-22.04
        steps:
            # https://github.com/dorny/paths-filter/tree/v3/
          - uses: dorny/paths-filter@v3
            id: filter
            with: 
              filters: |
                src:
                  - "**.dart"
                  - "**.yaml"
                  - "**.pubspec.lock"
          - name: Comment
            if: ${{ needs.pre-check.outputs.src  == 'false' }}
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              gh pr comment ${{ github.event.number }} --body "$(cat comment.md)"
            
    check:
        needs: pre-check
        if: ${{ needs.pre-check.outputs.src == 'true' }}
        runs-on: ubuntu-22.04
        timeout-minutes: 10
        steps:
            # https://github.com/actions/checkout/tree/v4/
          - name: Check out the code
            uses: actions/checkout@v4
            
          - name: Setup Application Runtime
            uses: ./.github/actions/setup-application-runtime

              # https://github.com/invertase/github-action-dart-analyzer/tree/v3/
          - name: Report custom_lint result
            run: |
              echo "::add-matcher::.github/problem_matchers/custom_lint.json"
              melos run report_custom_lint:ci --no-select || result=$?
              echo "::remove-matcher owner=custom_lint::"

              if [ -n "$result" ]; then
                exit 1
              fi

          - name: Report custom_lint result
            run: dart run custom_lint

          - name: Check format
            run: dart format -o none --set-exit-if-changed .

          - name: Run test
            run: flutter test --no-pub --machine > test_report.log
            continue-on-error: true

          - name: Upload test report
            uses: dorny/test-reporter@v1
            with:
              name: "flutter test"
              path: test_report.log
              reporter: "flutter-json"
              fail-on-error: "true"
            